@startuml

' left to right direction

database DB as db

agent Agenda as calendar
agent Evento as event_instance

actor Aluno as student

boundary "Página da agenda" as calendar_page

student -right->  calendar_page: "1. Solicitar criação de evento"
calendar -> event_instance: "1.1.1. Criar instancia"
event_instance .> calendar: "1.1.2. Retorna instancia criada"
db .right.> calendar: "1.2.2. Sucesso\n ou falha"
calendar -left-> db: "1.2.1. Salva evento criado no banco de dados"
calendar .up.> calendar_page: "1.3. Exibir\n novo evento
calendar_page -down-> calendar: "1.1. criarEvento(titulo, descricao, datas_repeticao[])"

@enduml
